<?php
require_once "config/database.php";
function setting($key,$default=''){global $pdo;$st=$pdo->prepare("SELECT value FROM settings WHERE `key`=?");$st->execute([$key]);return $st->fetchColumn() ?: $default;}
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$school=setting('school_name',"Gyandayini Girls’ Academy"); $trust=setting('trust_name',"Satya Bhama Educational Trust");
$address=setting('address',"Paramapur, Akelwa, Varanasi – 221302"); $aff=setting('affiliation',"A Co-Educational English Medium School, Affiliated to U.P. Government");
$email=setting('email',"gyandayinigirlsacademy@gmail.com");$phone=setting('phone',"9473528689");$fb=setting('facebook',"https://www.facebook.com/gyandayiniacademy");$ig=setting('instagram',"https://www.instagram.com/gyandayiniacademyakelwan/");
$announcement=setting('announcement',"Admissions & school updates — visit the academy office for current information.");
$facilities=$pdo->query("SELECT * FROM facilities ORDER BY sort_order,id")->fetchAll();
$events=$pdo->query("SELECT * FROM events ORDER BY event_date ASC LIMIT 4")->fetchAll();
$news=$pdo->query("SELECT * FROM news ORDER BY published_on DESC,id DESC LIMIT 4")->fetchAll();
$gallery=$pdo->query("SELECT * FROM gallery ORDER BY id DESC LIMIT 6")->fetchAll();
$rankers=$pdo->query("SELECT * FROM result_rankers WHERE active=1 ORDER BY sort_order,id")->fetchAll();
$cbseLinks=$pdo->query("SELECT * FROM cbse_links WHERE active=1 ORDER BY sort_order,id")->fetchAll();
$pages=$pdo->query("SELECT * FROM pages")->fetchAll();$page=[];foreach($pages as $p)$page[$p['slug']]=$p;
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($school)?> | Official Website</title><link rel="stylesheet" href="<?=rtrim(dirname($_SERVER['SCRIPT_NAME']),'/')?>/css/style.css"></head><body>
<header class="site-header">
<div class="topbar"><div class="container topbar-in"><span>📍 <?=e($address)?></span><span>✉ <?=e($email)?> &nbsp; | &nbsp; ☎ <?=e($phone)?></span></div></div>
<div class="brandbar container"><a class="school-brand" href="index.php"><img src="assets/images/gga-logo.png"><div><div class="school-name"><?=e($school)?></div><div class="trust">Under the aegis of <?=e($trust)?></div><div class="aff"><?=e($aff)?></div></div></a><div class="trust-brand"><img src="assets/images/trust-logo.png"><span><?=e($trust)?></span></div></div>
<nav class="nav"><div class="container nav-in"><button class="nav-toggle">☰ Menu</button><div class="nav-links"><a class="active" href="index.php">Home</a><div class="dropdown"><a href="#">About Us ▾</a><div class="dropmenu"><a href="about.php">About School</a><a href="message.php?slug=mission-vision">Mission & Vision</a><a href="message.php?slug=manager-message">Manager Message</a><a href="message.php?slug=principal-message">Principal Message</a><a href="documents.php">Mandatory Public Disclosure</a></div></div><a href="admission.php">Admission</a><a href="cbse.php">CBSE Details</a><a href="facilities.php">Facilities</a><a href="downloads.php">Downloads</a><a href="gallery.php">Gallery</a><a href="contact.php">Contact</a></div><a class="nav-cta" href="tc-verification.php">TC Verification →</a></div></nav>
</header>
<div class="ticker"><div class="container ticker-in"><b>📢 ANNOUNCEMENT</b><div class="marquee"><span><?=e($announcement)?></span></div></div></div>
<section class="hero"><div class="hero-bg"></div><div class="container hero-content"><div class="hero-copy"><span class="eyebrow">ज्ञान • संस्कार • व्यक्तित्व</span><h1>Empowering Every <em>Dream</em> To Grow</h1><p><?=e($aff)?>. A nurturing environment for learning, creativity, character and confidence.</p><div class="hero-actions"><a class="btn primary" href="admission.php">Explore Admission</a><a class="btn ghost" href="about.php">Discover Our School</a></div></div><div class="hero-trust"><img src="assets/images/trust-logo.png"><strong><?=e($trust)?></strong><small>Education • Values • Excellence</small></div></div></section>
<section class="section"><div class="container"><div class="section-head"><span class="eyebrow">Welcome to GGA</span><h2>A School That Nurtures <span>Every Possibility</span></h2><p><?=e($page['about-school']['content']??"Gyandayini Girls’ Academy is committed to providing a caring, disciplined and inspiring learning environment.")?></p></div><div class="stats"><div><strong>12+</strong><span>Learning Facilities</span></div><div><strong>360°</strong><span>Holistic Development</span></div><div><strong>100%</strong><span>Care & Guidance</span></div><div><strong>∞</strong><span>Dreams to Pursue</span></div></div></div></section>
<section class="section soft"><div class="container"><div class="section-head"><span class="eyebrow">School Facilities</span><h2>Learning Beyond the Classroom</h2><p>Explore 8 selected facilities below. Click the button to view the complete facilities section.</p></div><div class="facility-grid"><?php foreach(array_slice($facilities,0,8) as $f): ?><article class="facility-card reveal"><img src="<?=e($f['image'])?>" alt="<?=e($f['title'])?>"><div class="facility-body"><div class="facility-icon"><?=e($f['icon'])?></div><h3><?=e($f['title'])?></h3><p><?=e($f['description'])?></p></div></article><?php endforeach;?></div><div class="center-action"><a class="btn primary" href="facilities.php">View All Facilities →</a></div></div></section>
<section class="section"><div class="container split"><div><span class="eyebrow">Messages</span><h2>Guidance With Purpose</h2><p><?=e($page['principal-message']['content']??"Our leadership team works to build a positive, progressive and student-centred learning culture.")?></p><a class="text-link" href="message.php?slug=principal-message">Read Principal’s Message →</a></div><div class="message-preview"><img src="<?=e($page['principal-message']['image']??'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=85')?>"><div><b>Principal’s Message</b><span>Inspiring learning, values and confidence.</span></div></div></div></section>
<section class="section result-section"><div class="container"><div class="section-head"><span class="eyebrow">Academic Excellence</span><h2>Nursery – Class 8 Result Rankers</h2><p>Result ranker banners from Nursery, LKG, UKG and Class 1–8 are displayed here in an automatic scrolling banner.</p></div><?php if($rankers): ?><div class="ranker-marquee"><div class="ranker-track"><?php foreach($rankers as $r): ?><a class="ranker-slide" href="<?=e($r['image'])?>" target="_blank"><img src="<?=e($r['image'])?>" alt="<?=e($r['class_name'].' '.$r['title'])?>"><div><b><?=e($r['class_name'])?></b><span><?=e($r['title'])?> · <?=e($r['session_name'])?></span></div></a><?php endforeach; ?><?php foreach($rankers as $r): ?><a class="ranker-slide" href="<?=e($r['image'])?>" target="_blank"><img src="<?=e($r['image'])?>" alt="<?=e($r['class_name'].' '. $r['title'])?>"><div><b><?=e($r['class_name'])?></b><span><?=e($r['title'])?> · <?=e($r['session_name'])?></span></div></a><?php endforeach; ?></div></div><?php else: ?><div class="empty-banner">Result ranker banners will appear here after the Admin uploads them.</div><?php endif; ?></div></section>
<section class="section"><div class="container"><div class="section-head"><span class="eyebrow">CBSE Quick Links</span><h2>Important CBSE Websites</h2><p>Quick access to important official CBSE services and portals.</p></div><div class="cbse-link-grid"><?php foreach($cbseLinks as $l): ?><a class="cbse-link" href="<?=e($l['url'])?>" target="_blank" rel="noopener"><span><?=e($l['icon'])?></span><div><b><?=e($l['title'])?></b><small>Visit Official Website ↗</small></div></a><?php endforeach;?></div></div></section>
<section class="section soft"><div class="container"><div class="section-head"><span class="eyebrow">Upcoming</span><h2>Events & Activities</h2></div><div class="event-grid"><?php foreach($events as $ev): ?><article class="event-card"><img src="<?=e($ev['image'])?>"><div><small><?=e($ev['event_date'])?> · <?=e($ev['location'])?></small><h3><?=e($ev['title'])?></h3><p><?=e($ev['description'])?></p></div></article><?php endforeach;?></div></div></section>
<section class="section"><div class="container"><div class="section-head"><span class="eyebrow">Latest News</span><h2>School Updates</h2></div><div class="news-grid"><?php foreach($news as $n): ?><article class="news-card"><img src="<?=e($n['image'])?>"><div><small><?=e($n['published_on'])?></small><h3><?=e($n['title'])?></h3><p><?=e($n['excerpt'])?></p></div></article><?php endforeach;?></div></div></section>
<section class="section gallery-strip"><div class="container"><div class="section-head"><span class="eyebrow">Gallery</span><h2>Moments at GGA</h2></div><div class="mini-gallery"><?php foreach($gallery as $g): ?><a href="gallery.php"><img src="<?=e($g['image'])?>" alt="<?=e($g['title'])?>"></a><?php endforeach;?></div></div></section>
<footer class="footer"><div class="container footer-grid"><div><img class="footer-logo" src="assets/images/gga-logo.png"><h3><?=e($school)?></h3><p>Under the aegis of <?=e($trust)?></p></div><div><h4>Quick Links</h4><a href="about.php">About School</a><a href="admission.php">Admission</a><a href="facilities.php">Facilities</a><a href="gallery.php">Gallery</a></div><div><h4>Contact</h4><p>📍 <?=e($address)?></p><p>✉ <?=e($email)?></p><p>☎ <?=e($phone)?></p></div><div><h4>Follow</h4><a href="<?=e($fb)?>" target="_blank">Facebook</a><a href="<?=e($ig)?>" target="_blank">Instagram</a></div></div><div class="copyright">© <?=date('Y')?> <?=e($school)?>. All Rights Reserved.</div></footer>
<script src="js/site.js"></script></body></html>
