<?php $title="Downloads & Academic Resources"; require "_top.php";
function upload_download(){if(empty($_FILES['file']['name'])||$_FILES['file']['error']!==UPLOAD_ERR_OK)return ''; $dir=dirname(__DIR__).'/uploads/downloads';if(!is_dir($dir))mkdir($dir,0775,true);$ext=strtolower(pathinfo($_FILES['file']['name'],PATHINFO_EXTENSION));$allowed=['pdf','jpg','jpeg','png','webp','doc','docx','xls','xlsx'];if(!in_array($ext,$allowed,true))return ''; $name=uniqid('doc_',true).'.'.$ext;return move_uploaded_file($_FILES['file']['tmp_name'],$dir.'/'.$name)?'uploads/downloads/'.$name:'';}
if(isset($_POST['delete'])){$pdo->prepare("DELETE FROM downloads WHERE id=?")->execute([(int)$_POST['delete']]);}
if(isset($_POST['save'])){$id=(int)($_POST['id']??0);$file=trim($_POST['old_file']??'');if(trim($_POST['file_url']??''))$file=trim($_POST['file_url']);$up=upload_download();if($up)$file=$up;if($id){$pdo->prepare("UPDATE downloads SET title=?,file_url=?,category=?,class_name=? WHERE id=?")->execute([trim($_POST['title']),$file,trim($_POST['category']),trim($_POST['class_name']),$id]);}else{$pdo->prepare("INSERT INTO downloads(title,file_url,category,class_name) VALUES(?,?,?,?)")->execute([trim($_POST['title']),$file,trim($_POST['category']),trim($_POST['class_name'])]);}}
$edit=null;if(isset($_GET['edit'])){$st=$pdo->prepare('SELECT * FROM downloads WHERE id=?');$st->execute([(int)$_GET['edit']]);$edit=$st->fetch();}
$rows=$pdo->query("SELECT * FROM downloads ORDER BY category,id DESC")->fetchAll();
$classes=['Nursery','LKG','UKG'];for($i=1;$i<=8;$i++)$classes[]="Class $i";
?>
<div class="panel"><h2><?= $edit?'Edit Resource':'Add School Calendar / Syllabus / Download'?></h2><p class="muted">Upload a file or enter a file URL. Syllabus can be assigned to Nursery, LKG, UKG or Class 1–8.</p><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="id" value="<?=$edit['id']??0?>"><input type="hidden" name="old_file" value="<?=e($edit['file_url']??'')?>"><label>Title<input name="title" required value="<?=e($edit['title']??'')?>"></label><label>Category<select name="category"><option <?=($edit['category']??'')==='Academic'?'selected':''?>>Academic</option><option <?=($edit['category']??'')==='School Calendar'?'selected':''?>>School Calendar</option><option <?=($edit['category']??'')==='Syllabus'?'selected':''?>>Syllabus</option><option <?=($edit['category']??'')==='Online Service'?'selected':''?>>Online Service</option><option <?=($edit['category']??'')==='Other'?'selected':''?>>Other</option></select></label><label>Class (for Syllabus)<select name="class_name"><option value="">All / Not Applicable</option><?php foreach($classes as $c): ?><option value="<?=e($c)?>" <?=($edit['class_name']??'')===$c?'selected':''?>><?=e($c)?></option><?php endforeach;?></select></label><label>Upload File (PDF/Image/Office)<input type="file" name="file"></label><label class="full">Or File URL<input name="file_url" value="<?=e($edit['file_url']??'')?>" placeholder="uploads/downloads/file.pdf"></label><button class="primary" name="save">Save Resource</button></form></div>
<div class="table-wrap panel"><table><tr><th>Title</th><th>Category</th><th>Class</th><th>File</th><th>Action</th></tr><?php foreach($rows as $r): ?><tr><td><b><?=e($r['title'])?></b></td><td><?=e($r['category'])?></td><td><?=e($r['class_name']??'')?></td><td><?php if($r['file_url']): ?><a href="../<?=e($r['file_url'])?>" target="_blank">View</a><?php endif;?></td><td><a href="?edit=<?=$r['id']?>">Edit</a> <form method="post" style="display:inline"><button class="link danger" name="delete" value="<?=$r['id']?>">Delete</button></form></td></tr><?php endforeach;?></table></div>
<?php require "_bottom.php"; ?>
